export const genres = [
    "art",
    "biography",
    "business",
    "chick lit",
    "children",
    "christian",
    "classics",
    "comics",
    "contemporary",
    "cookbooks",
    "crime",
    "ebooks",
    "fantasy",
    "fiction",
    "lgbtq+",
    "graphic novels",
    "historical fiction",
    "history",
    "horror",
    "humor",
    "manga",
    "memoir",
    "music",
    "mystery",
    "nonfiction",
    "paranormal",
    "philosophy",
    "poetry",
    "psychology",
    "religion",
    "romance",
    "science",
    "science fiction",
    "self help",
    "suspense",
    "spirituality",
    "sports",
    "thriller",
    "travel",
    "young adult"
]